float:
  any:
  - base_args: ["@metric"]
    constructor: MH
    disabled: false
    docker_tag: p2hnns-benchmarks-mh
    module: p2hnns_benchmarks.algorithms.mh
    name: mh
    run_groups:
      MH:
        args: [
          [8, 16], #m projection vectors
          [64, 128, 256], # k hash functions
          [4, 8] #l hash tables
        ]
        query_args: [
          # [10000,50000,100000,300000,500000,800000,1000000,1100000,1150000] # candidates
          [5000, 10000]
        ]
