float:
  any:
  - base_args: ["@metric"]
    constructor: MH
    disabled: true
    docker_tag: p2hnns-benchmarks-mh
    module: p2hnns_benchmarks.algorithms.mh
    name: mh
    run_groups:
      MH:
        args: [[4, 6, 8], [8, 16, 32, 64, 128, 256], [2, 4, 6, 8, 10]]
        query_args: [[10000,50000,100000,300000,500000,800000,1000000,1100000,1150000]]
