float:
  any:
  - base_args: ['@metric']
    constructor: LinearScan
    disabled: false
    docker_tag: ann-benchmarks-linearscan
    module: ann_benchmarks.algorithms.linearscan
    name: linearscan
    run_groups:
      base:
        args: []
        query_args: []