float:
  any:
    - base_args: ['@metric']
      constructor: MQH
      disabled: false
      docker_tag: ann-benchmarks-mqh
      module: ann_benchmarks.algorithms.mqh
      name: mqh
      run_groups:
        mqh-test:
          args: [
              [16], # [M2 - number of subcodebooks]
              [4], # [level - number of levels]
              [1], # [m_level - number of hash tables per level]
              [64], # [m_num - number of bits per hash table]
          ]
          query_args: [
              [5], # [l0 - hash offset]
              [0.3], # [delta - filtering parameter]
              [0,1], # [flag - 0 for approximate, 1 for precise]
              [1] # max_candidates OBS: Only used when no external candidates passed
          ]

    - base_args: ['@metric']
      constructor: BT_MQH
      disabled: false
      docker_tag: ann-benchmarks-mqh
      module: ann_benchmarks.algorithms.mqh
      name: bt-mqh
      run_groups:
        BT_MQH:
          args: [
              [10], # [max_leaf_size - BTree parameter]
              [16], # [M2 - number of subcodebooks]
              [4], # [level - number of levels]
              [1], # [m_level - number of hash tables per level]
              [64], # [m_num - number of bits per hash table]
          ]
          query_args: [
              [2000000], # [candidates - number of examined candidates]
              [1000], # [initial_topk - parameter for BTree]
              [5], # [l0 - hash offset]
              [0.3], # [delta - filtering parameter]
              [0,1], # [flag - 0 for approximate, 1 for precise]
              [1] # max_candidates OBS: Only used when no external candidates passed
          ]

    - base_args: ['@metric']
      constructor: MH_MQH
      disabled: true
      docker_tag: ann-benchmarks-mqh
      module: ann_benchmarks.algorithms.mqh
      name: mh-mqh
      run_groups:
        MH_MQH:
          args: [
              [4, 6, 8], # [M_proj_vectors - MH parameter]
              [8, 16, 32, 64, 128, 256], # [m_single_hashers - MH parameter]
              [2, 4, 6, 8, 10], # [l_hash_tables - MH parameter]
              [16], # [M2 - number of subcodebooks]
              [4], # [level - number of levels]
              [1], # [m_level - number of hash tables per level]
              [64], # [m_num - number of bits per hash table]
          ]
          query_args: [
              [10000, 20000, 35000, 50000], # [candidates - number of examined candidates]
              [10000], # [initial_topk - parameter for MH]
              [5], # [l0 - hash offset]
              [0.3], # [delta - filtering parameter]
              [0,1], # [flag - 0 for approximate, 1 for precise]
              [1] # max_candidates OBS: Only used when no external candidates passed
          ]