# bit:
#   jaccard:
#   - base_args: ['@metric']
#     constructor: BruteForceBLAS
#     disabled: false
#     docker_tag: p2hnns-benchmarks-bruteforce
#     module: p2hnns_benchmarks.algorithms.bruteforce
#     name: bf
#     run_groups:
#       base:
#         args: {}
float:
  any:
  - base_args: ['@metric']
    constructor: BruteForce
    disabled: false
    docker_tag: p2hnns-benchmarks-bruteforce
    module: p2hnns_benchmarks.algorithms.bruteforce
    name: bruteforce
    run_groups:
      empty:
        args: []
  - base_args: ['@metric']
    constructor: BruteForceBLAS
    disabled: true
    docker_tag: p2hnns-benchmarks-bruteforce
    module: p2hnns_benchmarks.algorithms.bruteforce
    name: bruteforce-blas
    run_groups:
      empty:
        args: []
