float:
  any:
  - base_args: ['@metric']
    constructor: B_tree
    disabled: false
    docker_tag: p2hnns-benchmarks-balltree
    module: p2hnns_benchmarks.algorithms.balltree
    name: balltree
    run_groups:
      B_tree:
          args: [[25, 50, 100, 500, 1000, 5000]]
          query_args: [[10000, 20000, 35000, 50000]]

