float:
  any:
  - base_args: ['@metric']
    constructor: BH
    disabled: true
    docker_tag: p2hnns-benchmarks-bh
    module: p2hnns_benchmarks.algorithms.bh
    name: bh
    run_groups:
      BH:
        args: [[8, 16, 32, 64, 128, 256], [2, 4, 6, 8, 10]] 
        query_args: [[10000,50000,100000,300000,500000,800000,1000000,1100000,1150000]]