float:
  any:
  - base_args: ['@metric']
    constructor: BC_tree
    disabled: false
    docker_tag: p2hnns-benchmarks-bctree
    module: p2hnns_benchmarks.algorithms.bctree
    name: bctree
    run_groups:
      BC_tree:
          args: [[100, 500, 1000, 5000, 10000]]
          query_args: [[1000, 5000, 10000, 40000]]