float:
  any:
  - base_args: ['@metric']
    constructor: BruteForceGo
    disabled: false
    docker_tag: ann-benchmarks-bruteforcego
    module: ann_benchmarks.algorithms.bruteforcego
    name: bruteforcego
    run_groups:
      empty:
        args: []
