float:
  any:
  - base_args: ['@metric']
    constructor: BH
    disabled: false
    docker_tag: ann-benchmarks-bh
    module: ann_benchmarks.algorithms.bh
    name: bh
    run_groups:
      FH:
        args: [[16, 32], [2,4,8]]
        query_args: [[1000, 5000, 10000, 40000]]