float:
  any:
  - base_args: ['@metric']
    constructor: B_tree
    disabled: false
    docker_tag: ann-benchmarks-balltree
    module: ann_benchmarks.algorithms.balltree
    name: balltree
    run_groups:
      B_tree:
          args: [[100, 10000]]
          query_args: [[10]]