float:
  any:
  - base_args: ['@metric']
    constructor: FH
    disabled: false
    docker_tag: ann-benchmarks-fh
    module: ann_benchmarks.algorithms.fh
    name: fh
    run_groups:
      FH:
        args:
          m_hashers: [8] #, 16, 32, 64, 128, 256]
          scale_factor: [1] #, 2, 4, 8]
          sep_threshold: [1] #, 1, 3]
          candidates: [10] #, 50, 100, 500, 1000, 5000, 10000, 20000, 30000, 40000]