float:
  any:
  - base_args: ['@metric']
    constructor: BC_tree
    disabled: false
    docker_tag: ann-benchmarks-bctree
    module: ann_benchmarks.algorithms.bctree
    name: bctree
    run_groups:
      BC_tree:
        args:
          leaf_size: [100, 200, 500, 1000, 2000, 5000]