float:
  any:
  - base_args: ['@metric']
    constructor: BC_tree
    disabled: false
    docker_tag: ann-benchmarks-bctree
    module: ann_benchmarks.algorithms.bctree
    name: bctree
    run_groups:
      BC_tree:
          args: [[100, 500]]
          query_args: [[1000, 5000, 10000, 40000]]