float:
  any:
  - base_args: ['@metric']
    constructor: EH
    disabled: false
    docker_tag: p2hnns-benchmarks-eh
    module: p2hnns_benchmarks.algorithms.eh
    name: eh
    run_groups:
      EH:
        args: [
          [4, 8, 16], # bit string length
          [4,8], #l hash tables
        ]
        query_args: [
          [5000, 10000, 20000, 50000]
        ]