float:
  any:
  - base_args: ['@metric']
    constructor: NH
    disabled: false
    docker_tag: p2hnns-benchmarks-nh
    module: p2hnns_benchmarks.algorithms.nh
    name: nh
    run_groups:
      NH:
        args: [[16, 32, 64], [1, 2, 4, 8]]
        query_args: [[1000, 5000, 10000, 40000]]
        # args:
        #   m_hashers: [8, 16, 32, 64] #, 128, 256]
        #   scale_factor: [1] #, 2, 4, 8]
        #   candidates: [10, 50, 100, 500, 1000, 5000, 10000, 20000, 30000, 40000]